### ISSUE TITLE
Does this support hierarchy in Dimensions?

### ISSUE THREAD

**Issue by ThomasPCG** [fibo/OLAP-cube#1]
Hi,

It seems like there is no concept of hierarchy within the dimension?
For example, I have a "Destination" dimension. In the dimension, I have the following hierarchy.
America
	USA
	Canada
	Brazil
	Venezuela
	Mexico
Europe
	United Kingdom
	Norway
	Denmark
	Germany
	Portugal
Asia
	Japan
	China
	Russia
	Cambodia
	Thailand
	Indonesia
	Malaysia

If I pull the data of the aggregated element in the hierarchy, I hope to get the summation of the values within the hierarchy.

Example, if I have the following rates for Europe,
United Kingdom: 100
Norway: 200
Denmark: 300
Germany: 400
Portugal: 500
Retrieving Europe rates will be the summation which is 1,500.

Is this currently supported?

**Comment by fibo** [comment]
Hi, thank you very much for you feedback. It is a very good point and there is an OLAP function called `rollup` that does exactly what you need. I have implemented and it will be available in a release that I have just published on the npm registry.

Check out the documentation of [rollup method](https://github.com/fibo/OLAP-cube#tablerollupdimension-aggregator) which is similar to the use case you provided.

Please let me know if it does not work, or you need support...
and thank you again for your idea.

Ciaooo
