### ISSUE TITLE
Rollup Support 2 dimension filter?

### ISSUE THREAD

**Issue by kstan79** [fibo/OLAP-cube#2]
Hi, I wish to perform some calculation with multi dimension filter, is it supported? And if it is supported can share with me? Assume data as below:

["id", "country", "client", "location","qty", "total"]
Data
[
[1, 'US' , 'company 1', 'A', 1, 100],
[2, 'US' , 'company 2', 'B', 3, 30],
[3, 'TH' , 'company 2', 'A', 2, 40],
.... and much more data ...
]

I wish to rollup sum qty and total, with more then 1 dimension ['country','location'], end result I wish to achieve as below:
[['US', 'A', 1, 100],['US', 'B', 3, 30],['TH', 'A', 2, 40],]

Thanks in advance.

**Comment by fibo** [comment]
It is an interesting example, thank you for your contribution. I would glad to provide a solution.

In this particular use case, it seems that dimension *country* could be determined by the *location*.

Can you confirm this? If yes I think I can try to write down a code that rolls up on *location* then return data as desired, determining the country by its location.

**Comment by kstan79** [comment]
hi fibo,

thanks prompt reply, you can assume country and location is 2 totally different kind of dimension. Example of location can be 'accept', 'wip' or 'reject'. 
If the filter can accept similar parameter as below will be nice:
**Array of json object**
```
[
{location:'Wip"},
{country: 'US', 'location':'Reject'},
 {contry:'SG'},{country:'UK'} ...] 
```
 or 
**Json object** 
with array of filter value:
`{  location:['Wip','Reject'...],  country: ['US','SG','TH']}`

**Comment by fibo** [comment]
Your use case looks really specific, the rollup definition involves only one dimension. Hence I think it does not worth to extend current implementation provided by this package.

I think the best approach to get your job done would be to create a custom class thst extends [model/Table](https://github.com/fibo/OLAP-cube/blob/master/model/Table.js).

You can start coding it then if you link ot here, adding also a complete input data and expected output data in json format to write a test, I can try to help.

Good luck.
